In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr.ndim #provides dimension of the array

2

In [10]:
arr.itemsize #tells about the size carried by each element of the array

8

In [11]:
arr.dtype #tells about the data type of each element of the array

dtype('int64')

In [14]:
arr=arr.reshape(6,1) #reshape is used to reshape the array
arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
brr=np.linspace(5,10,15)  #linspace will print 15 values from 5 to 10 which will be linearly spaced. means difference between consecutive elements will be same
print(brr)

[ 5.          5.35714286  5.71428571  6.07142857  6.42857143  6.78571429
  7.14285714  7.5         7.85714286  8.21428571  8.57142857  8.92857143
  9.28571429  9.64285714 10.        ]


In [18]:
maxalongaxis0=arr.max(axis=0)
print(maxalongaxis0)


[6]


Arithmetic Operations on the array

In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
#addition

[5 7 9]


In [20]:
print(a/b)
#division

[0.25 0.4  0.5 ]


In [23]:
print(np.vstack((a,b)))
#vertical stack. basically 2 arrays ko vertical ek ke upar ek rakh dega. elements ko add nhi karega 

[[1 2 3]
 [4 5 6]]


In [24]:
print(np.hstack((a,b)))
#horizontal stack. basically 2 arrays ko horizontally ek ke upar ek rakh dega. elements ko add nhi karega.

[1 2 3 4 5 6]


In [26]:
hrr=np.zeros((3,2),dtype=int)
print(hrr)
#creates a 3*2 matrix with all elements zero of data type int.

[[0 0]
 [0 0]
 [0 0]]


(3, 2)
